- setup.py
> new dependencies

- setup.py
This PR address #6 , 
This PR install the phonopy code (via pip) , and setup aiida code as phonopy@localhost. using the setup.py from the plugin
> setup phonopy and phonopy@localhost

- aiidalab_qe_vibroscopy/workflows/result.py
This PR adds a HTML table to display the Raman active frequencies and its labels.
> adding an html table to results to display active modes

- aiidalab_qe_vibroscopy/utils/raman/result.py
- aiidalab_qe_vibroscopy/workflows/result.py
This PR creates a widget containing the Raman active modes, and displays a nglview widget with a trajectory animating the mode.
> adding animations of the raman active modes

- aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
- aiidalab_qe_vibroscopy/workflows/workchain.py
This PR allow the plugin to deal with 1D and 2D StructureData
> Serial Run and 1D, 2D perioidicity

- aiidalab_qe_vibroscopy/utils/raman/result.py
- aiidalab_qe_vibroscopy/workflows/settings.py
- setup.py
- fixing https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/4
- fixing https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/16
> Some minor modifications

- aiidalab_qe_vibroscopy/workflows/settings.py
- aiidalab_qe_vibroscopy/workflows/workchain.py
This PR fix a small bug when loading the settings panel
> fix bug for calc_options dropdown being a str

- aiidalab_qe_vibroscopy/utils/raman/result.py
This PR fix a bug if the workchain doesnt have accuracy_4
> Accuracy_4 not present bug

- aiidalab_qe_vibroscopy/app/result.py
I added the "Phonon properties" and "Raman/IR" tabs.
> Adding tabs for each property section of phonons.

- aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
> VibroWorkChain run_phonopy logic modifications

- aiidalab_qe_vibroscopy/app/__init__.py
- aiidalab_qe_vibroscopy/app/result.py
- aiidalab_qe_vibroscopy/app/workchain.py
- aiidalab_qe_vibroscopy/utils/harmonic/result.py
- aiidalab_qe_vibroscopy/utils/phonons/result.py
- aiidalab_qe_vibroscopy/utils/raman/result.py
- aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
merge once there is the new release
> removing unused Class, updating resources

- aiidalab_qe_vibroscopy/app/result.py
- aiidalab_qe_vibroscopy/utils/phonons/result.py
- aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
- phonopy_install.py
> Fix Results visualization

- aiidalab_qe_vibroscopy/app/result.py
> Fix Tab Titles for IR/Raman

- aiidalab_qe_vibroscopy/app/workchain.py
modification to be compatible with new version
> Walltime fix

- aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
closes https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/67
> Update vibroworkchain.py by lowering the mesh

- src/aiidalab_qe_vibroscopy/app/settings.py
> setting supercell values from previous calculation

- src/aiidalab_qe_vibroscopy/app/result.py
- src/aiidalab_qe_vibroscopy/utils/euphonic/__init__.py
- src/aiidalab_qe_vibroscopy/utils/phonons/result.py
This fix the third point of https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/38
> Bands, Pdos, Thermo are now downloadable

- README.md
This fixes https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/80
> User install is suggested in the README

- src/aiidalab_qe_vibroscopy/utils/phonons/result.py
https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/96
> This fixes

- pyproject.toml
- src/aiidalab_qe_vibroscopy/utils/raman/result.py
In this PR we control with the amplitude the length of the arrows ,
> upgrade weas_widget factor control

- src/aiidalab_qe_vibroscopy/app/__init__.py
- src/aiidalab_qe_vibroscopy/app/code.py
Here, we are updating the resources tab for the vibroscopy plugin given the recent updates from aiidalab-qe.
Now is compatible and it displays and upload the resources used
> updating resources with new classes from aiidalab-qe

- src/aiidalab_qe_vibroscopy/app/code.py
- src/aiidalab_qe_vibroscopy/app/model.py
Since there was a modification in qe app, the titles were not being displayed, this fixes that
> setting titles for code and settings

- src/aiidalab_qe_vibroscopy/app/__init__.py
- src/aiidalab_qe_vibroscopy/app/guides/0_phonons+neutrons.html
- src/aiidalab_qe_vibroscopy/app/guides/1_Raman+IR+dielectric.html
- src/aiidalab_qe_vibroscopy/app/guides/2_phonons+Raman+IR+dielectric+neutrons.html
- src/aiidalab_qe_vibroscopy/app/result/result.py
- src/aiidalab_qe_vibroscopy/app/settings.py
- src/aiidalab_qe_vibroscopy/app/widgets/dielectricwidget.py
- src/aiidalab_qe_vibroscopy/app/widgets/euphonicwidget.py
- src/aiidalab_qe_vibroscopy/app/widgets/ir_ramanwidget.py
- src/aiidalab_qe_vibroscopy/app/widgets/phononwidget.py
This fixes https://github.com/mikibonacci/aiidalab-qe-vibroscopy/issues/130
> In-app guides

- src/aiidalab_qe_vibroscopy/app/widgets/ramanmodel.py
- src/aiidalab_qe_vibroscopy/app/widgets/ramanwidget.py
> Include NAC direction IRRaman Results

- src/aiidalab_qe_vibroscopy/app/model.py
- src/aiidalab_qe_vibroscopy/app/settings.py
- src/aiidalab_qe_vibroscopy/app/workchain.py
- src/aiidalab_qe_vibroscopy/workflows/vibroworkchain.py
here we include a widget to control the Max temperature to integrate in the thermodynamic properties ,
> Feature. Controling max temperature thermo props
